gateways:
    local:
        connection:
            type: duckdb
            catalogs:
                persistent: 'local.duckdb'
                ephemeral: ':memory:'
        state_connection:
            type: postgres
            host: localhost
            user: postgres
            password: postgres
            port: 5432
            database: postgres

default_gateway: local

model_defaults:
    dialect: postgres
